### PR TITLE
Update BrowserContextStorageStateTests.cs

### PR DESCRIPTION
**Pull request by interiv**
bug fix

### CODE REVIEW

**Review by kblok — APPROVED** [review]
Thank you!

**Review by avodovnik — CHANGES_REQUESTED** [review]
`ShouldRoundTripThroughTheFile` is failing in tests - not sure this change is correct

**Comment by kblok** [comment]
@avodovnik. Yeah. I wouldn't merge this without the fix. But I'm working on that :)

**Comment by avodovnik** [comment]
@kblok yeah, I think this change just surfaced a problem in the test, but regardless, we need to fix it before merging/approving it

**Review by avodovnik — APPROVED** [review]
We can merge this after #1465 merges!

Thanks for the contribution and spotting a problem!

**Pull request merged**
