### PR TITLE
Initial docs using docfx

### PR DESCRIPTION
**Pull request by Meir017**
related to #157

### CODE REVIEW

**Comment by Meir017** [comment]
something is working https://meir017.github.io/playwright-sharp/api/index.html
image

**Comment by Meir017** [comment]
in order for this to work I had to do the steps of creating a secret described here - https://github.com/maxheld83/ghpages#secrets

**Comment by arjun27** [comment]
This is awesome! I'm wondering if we can set it up like in the Python repo: https://github.com/microsoft/playwright-python/blob/master/.github/workflows/deploy-docs.yml#L27

GITHUB_TOKEN is pre-configured on Actions agents.

**Comment by kblok** [comment]
I would follow this recipe to push to the gh_pages branch https://github.com/dotnetconfig/dotnet-config/blob/dev/.github/workflows/pages.yml

**Comment by kblok** [comment]
Another thing @Meir017. Only if it's a small flag, if not we can leave that for later.
http://www.puppeteersharp.com/ doesn't have a global search as https://dotnetconfig.org/
Could you check if that's easy to add?

**Comment by Meir017** [comment]
@kblok adding 
```json
"globalMetadata": {
      "_appTitle": "Playwright Sharp",
      "_enableSearch": true
    }
```
solved this :)
image

**Comment by kblok** [comment]
This is awesome!

**Comment by kblok** [comment]
I think that scope wise this is great.
I would make it build only on `tag`. So we show the docs of the published app. But I would merge it as is so we get the first doc up and running.

@Meir017 do you want to create a PR on https://github.com/kblok/playwright-sharp  so we make sure that the gh-pages branch works?

We would need to work on the home page @arjun27

**Comment by Meir017** [comment]
@kblok I created the PR on https://github.com/Meir017/playwright-sharp to make sure it works.
to verify that it works I added 
```yml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
```
so it will run for each commit :)
and you can see it here - https://meir017.github.io/playwright-sharp

**Review by kblok — APPROVED** [review]

**Comment by Meir017** [comment]
I think it's better to have the docs be built even without tags, this way even typo fixes will be deployed and won't wait for a version release

**Comment by kblok** [comment]
@Meir017 that's a fair point, but pushing an unshipped API to the official site won't be ok. No one will care about the docs from the master branch.
Can we add a manual trigger (https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) in case of a red alert?

>not sure it's possible with docfx but maybe we could add a way to view previous version docs similar to playwright

https://playwright.dev/ rocks. The search is awesome. It feels great. I would create markdowns based on the XML and use the same tool. But my ultimate dream is hosting our docs in docs.microsoft.com.

**Comment by Meir017** [comment]
@kblok now it can run manually too.
I copied the release part from playwright, is it correct?
image

**Comment by kblok** [comment]
@Meir017 sounds perfect!

**Pull request merged**
